/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
      extend: {
          "colors": {
              "on-primary-fixed": "#0d1c32",
              "on-tertiary-fixed": "#002019",
              "on-tertiary-container": "#00937a",
              "on-primary-fixed-variant": "#39475f",
              "inverse-on-surface": "#263049",
              "secondary-fixed": "#6ffbbe",
              "on-secondary": "#003824",
              "surface-container-high": "#1f2942",
              "error-container": "#93000a",
              "surface-container": "#151f37",
              "inverse-primary": "#515f78",
              "surface-variant": "#2a344d",
              "secondary-fixed-dim": "#4edea3",
              "secondary-container": "#00a572",
              "surface": "#08132a",
              "primary": "#b9c7e4",
              "surface-container-highest": "#2a344d",
              "inverse-surface": "#d9e2ff",
              "background": "#08132a",
              "on-tertiary": "#00382d",
              "primary-container": "#0a192f",
              "on-tertiary-fixed-variant": "#005142",
              "outline": "#8f9097",
              "surface-tint": "#b9c7e4",
              "primary-fixed-dim": "#b9c7e4",
              "on-primary": "#233148",
              "on-error": "#690005",
              "secondary": "#4edea3",
              "tertiary": "#38debb",
              "surface-container-lowest": "#030d25",
              "on-secondary-fixed": "#002113",
              "on-surface": "#d9e2ff",
              "on-surface-variant": "#c5c6cd",
              "tertiary-fixed-dim": "#38debb",
              "surface-bright": "#2f3952",
              "outline-variant": "#44474d",
              "surface-container-low": "#101b33",
              "on-primary-container": "#74829d",
              "on-secondary-fixed-variant": "#005236",
              "primary-fixed": "#d6e3ff",
              "error": "#ffb4ab",
              "on-background": "#d9e2ff",
              "tertiary-container": "#001e17",
              "surface-dim": "#08132a",
              "on-error-container": "#ffdad6",
              "tertiary-fixed": "#5ffbd6",
              "on-secondary-container": "#00311f"
          },
          "borderRadius": {
              "DEFAULT": "0.25rem",
              "lg": "0.5rem",
              "xl": "0.75rem",
              "full": "9999px"
          },
          "spacing": {
              "sm": "12px",
              "lg": "48px",
              "base": "8px",
              "xs": "4px",
              "xl": "80px",
              "container-max": "1200px",
              "gutter": "20px",
              "md": "24px"
          },
          "fontFamily": {
              "data-display": ["JetBrains Mono"],
              "body-md": ["Inter"],
              "headline-md": ["Inter"],
              "headline-lg": ["Inter"],
              "body-lg": ["Inter"],
              "headline-lg-mobile": ["Inter"],
              "label-caps": ["JetBrains Mono"]
          },
          "fontSize": {
              "data-display": ["20px", {"lineHeight": "24px", "fontWeight": "600"}],
              "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
              "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
              "headline-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
              "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
              "headline-lg-mobile": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700"}],
              "label-caps": ["12px", {"lineHeight": "16px", "letterSpacing": "0.1em", "fontWeight": "500"}]
          }
      },
  },
  plugins: [],
}
